### ISSUE TITLE
单ENB的MRO时间异常导致大包入库异常

### ISSUE THREAD

**Issue by zengqingbo** [zengqingbo/mroget#1]
celery任务处理异常导致 worker 退出

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/tasks.py", line 36, in handleBigZipfile
    maintodb(csvfile)
  File "/app/tasks.py", line 64, in maintodb
    raise e
  File "/app/tasks.py", line 59, in maintodb
    cur.execute("copy {} from '{}' WITH DELIMITER AS ',' NULL AS 'NIL' CSV;".format(tablename,filename) )
psycopg2.DataError: no partition for partitioning key
CONTEXT:  COPY nccounter, line 266: "2008-01-04 02:00:00.000,450201,115251458,NIL,NIL,NIL,1,NIL,NIL,NIL,NIL,NIL,2008-01-04 02:00:00.00"

**Comment by zengqingbo** [comment]
计划在大包入库过程中，捕获异常，并更新大包文件处理结果。
